apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd
  name: buildkitd
spec:
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
        container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined
    spec:
      containers:
# moby/buildkit:vX.Y.Z-rootless is executed as an unprivileged user (UID=1000).
# If you are using Debian (not Ubuntu) or Arch Linux kernel on each of kubelet nodes,
# `sudo sh -c "echo 1 > /proc/sys/kernel/unprivileged_userns_clone"` is required.
#
# Note that rootless mode does not support OverlayFS snapshotter unless using Ubuntu kernel.
# However, reflink-based Copy-on-Write can be enabled by mounting XFS volume on /home/user/.local/share/buildkit .
# The XFS volume needs to be formatted with `mkfs.xfs -m reflink=1`.
#
# Also note that rootless mode is known not to work on GCOS kernel: https://github.com/moby/buildkit/issues/879
#
# You can also use rootful moby/buildkit:vX.Y.Z instead.
      - image: moby/buildkit:v0.4.0-rootless@sha256:3877d091e65429f59919ed5591aaeb863b1889a5314bdfdba5ff9c0dfb2f3ed0
        args:
        - --addr
        - tcp://0.0.0.0:1234
# Disable PID namespace isolation across BuildKit daemon and build containers.
# To enable PID namespace isolation, you need to remove --oci-worker-no-process-sandbox and
# set securityContext.procMount to "Unmasked" (or set securityContext.privileged to true).
        - --oci-worker-no-process-sandbox
        name: buildkitd
        ports:
        - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buildkitd
  name: buildkitd
spec:
  ports:
  - port: 1234
    protocol: TCP
  selector:
    app: buildkitd 
