apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: buildkit
spec:
  parameters:
  - name: IMAGE
    description: Where to publish the resulting image
  - name: DOCKERFILE
    description: The name of the Dockerfile
    default: "Dockerfile"
  - name: PUSH
    description: Whether push or not
    default: "true"
  - name: DIRECTORY
    description: The directory containing the app
    default: "/workspace"
  - name: BUILDKIT_CLIENT_IMAGE
    description: The name of the BuildKit client (buildctl) image
    default: "moby/buildkit:v0.4.0-rootless@sha256:3877d091e65429f59919ed5591aaeb863b1889a5314bdfdba5ff9c0dfb2f3ed0"
  - name: BUILDKIT_DAEMON_ADDRESS
    description: The address of the BuildKit daemon (buildkitd) service
    default: "tcp://buildkitd:1234"
  steps:
  - name: build-and-push
    image: ${BUILDKIT_CLIENT_IMAGE}
    workingDir: ${DIRECTORY}
    command: ["buildctl", "--addr=${BUILDKIT_DAEMON_ADDRESS}", "build",
              "--progress=plain",
              "--frontend=dockerfile.v0",
              "--opt", "filename=${DOCKERFILE}",
              "--local", "context=.", "--local", "dockerfile=.",
              "--output", "type=image,name=${IMAGE},push=${PUSH}"]
#
# To enable distributed cache, add
#   --export-cache type=inline --import-cache type=registry,ref=${IMAGE}
# or
#   --export-cache type=local,dest=/your/nfs/volume --import-cache type=local,src=/your/nfs/volume
